name: Check PR Source Branch for Main

on:
  pull_request:
    branches:
      - main # main 브랜치로 들어오는 모든 PR에 대해 실행

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source branch is 'staging'
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}"
          TARGET_BRANCH="${{ github.base_ref }}"

          echo "Source Branch: $SOURCE_BRANCH"
          echo "Target Branch: $TARGET_BRANCH"

          if [[ "$TARGET_BRANCH" == "main" && "$SOURCE_BRANCH" != "staging" ]]; then
            echo "::error::Only pull requests from 'staging' branch are allowed to merge into 'main' branch."
            echo "Please create a pull request from 'staging' to 'main'."
            exit 1
          else
            echo "Source branch is valid for merging into main."
          fi
